### ISSUE TITLE
Unable to display image when resource is xml on android.

### ISSUE THREAD

**Issue by AbeHamade** [baskren/Forms9Patch#1]
In my andoird project Resources/drawable directory, I have a vector graphic, for example, outline_arrow.xml. When using the built in Xamarin Forms Image control, the image displays fine. However, when using Forms9Patch Image control, the image is not displayed at all. 

I don't know if this is a bug or a feature request? I assumed a bug since I expected to have all the same basic functionality.

**Comment by baskren** [comment]
Abe -

First, please accept my apologies for taking so darned long to reply.  I’ve been really swamped with work and family.  Can you send me a quick sample program that demonstrates what you are seeing?  There could be a lot of reasons for something like this - a sample program would go a long way to help me get to the bottom of things.

- Ben

**Comment by baskren** [comment]
@AbeHamade 

being able to accept Android vector images (.xml images) would be a new features.  I'll have to do some homework to see what it would take.

**Comment by baskren** [comment]
@Abe 

Forms9Patch is meant to be a platform independent implementation.  Android's VectorDrawable (xml) files could be platform independent but I haven't been able to find a resource that converts it to something I could use.  At this time, I just can't justify the amount of effort to build a VectorDrawable converter.
