### ISSUE TITLE
I've modified your source code.

### ISSUE THREAD

**Issue by KCarterSr** [baskren/Forms9Patch#10]
I have a MVVM crossplatform application and using Fontfamily with embedded fonts did not work.
Forms9Patch couldn't find the correct assembly with the embedded fonts.

After modifying the source code it now works.

I only tested and modified the code for UWP. I'll do the same for IOS, and Android when I
need those.

Below is the code I changed for UWP if you want to add the change to your source code.

FontService.cs BEFORE:

var appAsmName = Forms9Patch.ApplicationInfoService.Assembly.GetName().Name;

if (targetAsmNameA == appAsmName || targetAsmNameB == appAsmName)
{
    localStorageFileName = EmbeddedResourceCache.LocalStorageSubPathForEmbeddedResource(resourceId, Forms9Patch.ApplicationInfoService.Assembly);
    if (localStorageFileName!=null)
        uri = EmbeddedResourceCache.ApplicationUri(resourceId, Forms9Patch.ApplicationInfoService.Assembly);
}

FontService.cs AFTER:

var appAsmName = Forms9Patch.ApplicationInfoService.Assembly.GetName().Name;

// added these lines

localStorageFileName = EmbeddedResourceCache.LocalStorageSubPathForEmbeddedResource(resourceId, Forms9Patch.ApplicationInfoService.Assembly);
if (localStorageFileName!=null)
    uri = EmbeddedResourceCache.ApplicationUri(resourceId, Forms9Patch.ApplicationInfoService.Assembly);

//added localStorageFileName == null &&

if ( localStorageFileName == null && (targetAsmNameA == appAsmName || targetAsmNameB == appAsmName))
{
    localStorageFileName = EmbeddedResourceCache.LocalStorageSubPathForEmbeddedResource(resourceId, Forms9Patch.ApplicationInfoService.Assembly);
    if (localStorageFileName!=null)
        uri = EmbeddedResourceCache.ApplicationUri(resourceId, Forms9Patch.ApplicationInfoService.Assembly);
}

**Comment by baskren** [comment]
First, thank you for sharing this!  Greatly appreciated that you took the time to find the root cause.

Version 1.8 will be out later this week.  In it, the embedded resource locator is reworked - which addresses this issue (as well as a number of related issues).

**Comment by KCarterSr** [comment]
Thanks you.
