### ISSUE TITLE
Proper HTML in HtmlText?

### ISSUE THREAD

**Issue by alexthekid07** [baskren/Forms9Patch#11]
I am trying to use numerous Forms9Patch Labels to allow me to display HTML with varying styles on my page. I bind data like:
`<div style="color: #27aff3;">Sent</div>`
But it does not seem to appear at all. (nor with <span>)
I also tried:
`<font color="#27aff3">Sent</font>`

What is the proper way to color a portion of my text instead of all of it? Or simply divide chunks of text up?

**Comment by baskren** [comment]
@alexthekid07, take a look at the [HtmlLabelsPage in the Forms9PatchDemo App](https://github.com/baskren/Forms9PatchDemo/blob/master/Source/Pages.Code/HtmlLabelPage.cs)

```
new Forms9Patch.Label { HtmlText =  "\t with underline: <u><font color=\"#FF0000\">Red</font></u> plain"},
```

Also note that, through the use of CDATA, [you can put HtmlText into your XAML as well](https://github.com/baskren/Forms9PatchDemo/blob/master/Source/Pages.Xaml/XamlCDATA.xaml).

**Comment by baskren** [comment]
@alexthekid07  - I will be closing this issue if you cannot provide a demo project for evaluation and analysis.

**Comment by alexthekid07** [comment]
Sorry, I ended up using a different approach so I don't really have time to provide a demo. Thanks, though.
