### ISSUE TITLE
Label.LineHeight has no effect

### ISSUE THREAD

**Issue by sisve** [baskren/Forms9Patch#16]
Setting LineHeight has no effect on my iPhone, or the iOS Simulator. It does however render correctly using the builtin preview in Visual Studio 2019. (It seems the LabelRenderer doesn't look at the Label.LineHeight property at all.)

    <forms9:Label LineHeight="2.0" Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet tincidunt erat, ut varius quam." />

**Comment by baskren** [comment]
@sisve 

Sven -  I'm not 100% sure I'll be implementing LineHeight.  I need to study it some more as I'm not sure the AutoFit=Lines, Lines=n properties, and FontSize properties allows the same result.  Your insights on this would be appreciated.

**Comment by sisve** [comment]
A good example of how line-height works can be seen at https://developer.mozilla.org/en-US/docs/Web/CSS/line-height

I don't think that autofitting can be used in-place of line-height since the later adds distance between lines, which no example in the documentation shows the autofitting capable of.

**Comment by baskren** [comment]
Thank you for taking the time to get me up to speed.  Greatly appreciate this.  I'll need to take some time to scope out how to do this.  I'll let you know once I've figured it out.

**Comment by baskren** [comment]
@sisve 

I've added this to the iOS and Android versions of the source code.  Once I complete the implementation of this on the UWP version, I'll be releasing version 2.2.

**Comment by baskren** [comment]
Implemented in iOS and Android in version 2.2;

**Comment by sisve** [comment]
I can confirm that the line-height works as expected for me in 2.2. Thank you!
