### ISSUE TITLE
Image.Fill.None Question

### ISSUE THREAD

**Issue by juanp3053** [baskren/Forms9Patch#18]
Hello,

Is there any plans to implement an option for Image.Fill.None and conserve the Original Aspect Ration of the image, no resizing or tiling added?

Thanks for the help,
Juan

**Comment by baskren** [comment]
If I understand your question ... I originally was going to have a `None` state for the `AutoFill` property.   I then realized that when the `HorizontalOptions` and `VerticalOptions` properties are set to anything but `LayoutOptions.Fill`, logically it should do the same thing - sets the image to its original size and aspect ratio.   Additionally, when I thought about how the LayoutOptions properties are considered to be orthogonal to the AutoFill property, I knew there would only be confusion if I added a `None` state to `AutoFill`.
