### ISSUE TITLE
Frame height problem

### ISSUE THREAD

**Issue by mwallon** [baskren/Forms9Patch#19]
Hi, for some reason I get extra space in height bellow content when I use your fram but not with the forms frame, added pictures showing the problem. My code:
mainFrame = new Frame
            {
                BackgroundColor = Color.White,
                BorderColor = Globals.colGray,
                Padding = new Thickness(10 * scale, 15 * scale, 15 * scale, 10 * scale),
                Margin = new Thickness(10 * scale, 100 * scale, 10 * scale, 10 * scale),
                BorderRadius = (float)(5 * scale),
                OutlineWidth = (float)(5 * scale),
                VerticalOptions = LayoutOptions.StartAndExpand,
                HasShadow = true

            };
Do you know what might case this?
Second picture is with this plugin, the content inside the frame has azure background.

<img width="355" alt="Skärmavbild 2019-08-08 kl  14 31 21" src="https://user-images.githubusercontent.com/5337797/62703477-a055b200-b9e9-11e9-9027-98680d61ff19.png">
<img width="358" alt="Skärmavbild 2019-08-08 kl  14 32 28" src="https://user-images.githubusercontent.com/5337797/62703486-a8aded00-b9e9-11e9-8270-81da34777ea7.png">

**Comment by baskren** [comment]
Can you send me a demo project that illustrates this issue?

**Comment by baskren** [comment]
@mwallon  -  I will be closing this issue if you cannot provide a demo project.

**Comment by baskren** [comment]
No demo project provided.
