### ISSUE TITLE
ImageSource (re)binding not working

### ISSUE THREAD

**Issue by kicsiede** [baskren/Forms9Patch#2]
hello, 

when late binding the imagesource property the image doesn't update to its new value. the onsourcehanged event of imagesource should be handled, see OnSource* method implementations in https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Image.cs that take care of this issue.

also imagesource.image == null results in an exception.

**Comment by baskren** [comment]
@kicsiede  -  Can you share a demo app that replicates this behavior?   I ask because what you have observed has been tested for very thoroughly.  In fact, the StateButton relies upon this behavior to be able to perform quick transitions in background image.

**Comment by kicsiede** [comment]
here is a minimal example. for brevity i used a binding on bindingcontext. 
forms.image updates forms9.image does not. :(

[form9test.zip](https://github.com/baskren/Forms9Patch/files/2509725/form9test.zip)

**Comment by baskren** [comment]
@kicsiede Thank you for sharing an example.  I will be pushing an update later this evening with a fix.

**Comment by baskren** [comment]
Fixed in v 1.6.7.1
