### ISSUE TITLE
Can't resolve the reference 'System.Drawing.RectangleF'

### ISSUE THREAD

**Issue by Matmork** [baskren/Forms9Patch#20]
Hi,

iOS build fails with latest version 1.8.0.4, had to downgrade to 1.8.0.2

`Can't resolve the reference 'System.Drawing.RectangleF', referenced from the method 'Xamarin.Forms.Rectangle FormsGestures.iOS.iOSEventArgsHelper::GetViewPosition(System.Drawing.RectangleF)' in 'System.Drawing.Common`

**Comment by baskren** [comment]
Please send me a sample project that demonstrates this issue.  I cannot replicate and will close the issue without such a project.

**Comment by gsgou** [comment]
I can confirm. At least building with AppCenter / msbuild in Release presents the linking issue.
I ll try later to provide a sample.

**Comment by baskren** [comment]
@Matmork and @gsgou  -  Can either of you send a small VisualStudio solution that demonstrates this issue?  I cannot replicate and such a solution would go a long way to assure I am working on the right issue.  Sharing the solution as a github repo would be best.

**Comment by baskren** [comment]
Not enough information to pursue.

**Comment by gsgou** [comment]
@baskren I will provide you a sample coming weekend.

**Comment by baskren** [comment]
GREAT!

**Comment by baskren** [comment]
Sent you direct email with my AppCenter account

**Comment by baskren** [comment]
@gsgou and @Matmork  : Version 1.8.1 has been uploaded to NuGet.org.  It should address this issue.

**Comment by gsgou** [comment]
@baskren I can confirm it's fixed.
Thanks a lot for your message.
I am sorry i didn't make it to help as promised.

**Comment by baskren** [comment]
Great!  Thank you!
