### ISSUE TITLE
Compat issue on lollipop for Label

### ISSUE THREAD

**Issue by thomhubers** [baskren/Forms9Patch#21]
When using `<forms9Patch:Label FontSize="{Binding InfoTextFontSize}" HtmlText="{Binding InfoText}" LineBreakMode="WordWrap" Lines="0" AutoFit="None"/>`

This Exception is generated:
`Java.Lang.ClassNotFoundException: Didn't find class "android.text.StaticLayout$Builder"`

**Comment by baskren** [comment]
Take a look at the latest check-in on the dev branch.  It should be the fix for this issue.  Will be building an update NuGet in a few days (limited access to Wifi at the current time).

**Comment by thomhubers** [comment]
Much appreciated, thanks!

Met vriendelijke groet,
Thom Hubers

________________________________

**Comment by baskren** [comment]
1.9.0.3 released.
