### ISSUE TITLE
HTML Label Crash on IOS

### ISSUE THREAD

**Issue by OmarHassan25** [baskren/Forms9Patch#24]
My app crash on iOS devices when using HTML test for label like this sample, 

```
> <p dir="RTL" style="text-align:center">
>     <span style="font-size:11pt">
>     <span style="font-family:Calibri,sans-serif">
>       <strong><span style="font-size:21.0pt"><span style="font-family:&quot;Royal Arabic&quot;">test</span></span>
>     </strong>
>     </span>
>     </span>
> </p>
```

I am using Forms9Patch version 1.7,

**Comment by baskren** [comment]
@OmarHassan25 

Please share with me a sample project that demonstrates this issue.  There are two many possible reasons this might be happening and a demo project will go a long way in getting me focused on the root cause.  It would be best to share the project as a github repo.

**Comment by baskren** [comment]
Will close in a week if no demo project is provided.
