### ISSUE TITLE
1.8.0.5 Android - Constructor on type 'Forms9Patch.Droid.LabelRenderer' not found.

### ISSUE THREAD

**Issue by bdgza** [baskren/Forms9Patch#25]
Forms9Patch 1.8.0.5 on Xamarin Forms Android throws

> Constructor on type 'Forms9Patch.Droid.LabelRenderer' not found.

When loading a view with a SegmentedControl. Works fine on iOS. Downgrading to Forms9Patch 1.8.0.2 removes the error.

**Comment by baskren** [comment]
@bdgza -  Can you send me a sample project that demonstrates this issue.  There could be a number of causes and, without the sample project, I don't have a fighting chance of finding the root cause.

**Comment by bdgza** [comment]
Emailed sample project to you.

**Comment by baskren** [comment]
@bdgza -  I'll take a look this morning!

**Comment by baskren** [comment]
@bdgza :  

- work around: take the `Visual="Material"` parameter out of the `<classes:BaseContentPage>` tag in `DataCollectionPage.xaml`.
- root cause fix:  I'm still looking into it.

**Comment by baskren** [comment]
@bdgza :  Version 1.8.1 has been uploaded to NuGet.org.  It should address this issue.
