### ISSUE TITLE
Apart from Android/iOS/UWP, what about MacOS Apps

### ISSUE THREAD

**Issue by GKG4** [baskren/Forms9Patch#27]
I didnt know where to ask, so asking under issue sections

You mentioned that this supports Android/iOS/UWP
But what about MacOS Apps?

Can we build macOS apps, and if not, any possibility and ETA about future development for MacOS Support?

**Comment by baskren** [comment]
@GKG4 -

It's on my radar but I don't have a good answer at this time as I'm fully booked through the end of the year.
