### ISSUE TITLE
Forms9Patch:Frame doesn't render unless it contains another control

### ISSUE THREAD

**Issue by renzska** [baskren/Forms9Patch#29]
Forms9Patch:Frame doesn't render unless it contains another control.

This one renders:
```
  <forms9patch:Frame Margin="10,10,10,0"
                               Padding="4,6,4,6"
                               BackgroundColor="#ffffc0"
                               OutlineRadius="5"
                               HasShadow="true">
                <forms9patch:Label Text="Render Me" />
  </forms9patch:Frame>
```

This one does not:
```
 <forms9patch:Frame Margin="10,10,10,0"
                               Padding="4,6,4,6"
                               BackgroundColor="#ffffc0"
                               OutlineRadius="5"
                               HasShadow="true">
  </forms9patch:Frame>
```

I'm using this like a BoxView or a Xamarin.Forms.Frame, but with the extra properties. The Xamarin.Forms.Frame works in both cases.

Thanks for the continued work on this awesome library!

- John

**Comment by baskren** [comment]
@renzska -
Finally got around to looking at this. I've just fixed it in the BetterDispose branch and will be merging it to master next week.
