### ISSUE TITLE
After latest Xamarin.forms update I get a nullexception on Android

### ISSUE THREAD

**Issue by HTUlv412** [baskren/Forms9Patch#31]
I get a runtime unhandled nullexception after run this code, I'm working with the tooltips, only on Android project, iOS and UWP run correctly:

`                Forms9Patch.BubblePopup popup = new Forms9Patch.BubblePopup(btnInfo, true);
                Label content = new Label();
                content.Text = "Visit any ICTE Exchange website\nto find a QR code to access the\nICTE Wallet application";
                content.TextColor = Color.DarkBlue;
                popup.Content = content;
                popup.BackgroundColor = Color.White;
                popup.PointerDirection = Forms9Patch.PointerDirection.Right;
                popup.IsVisible = true;
`
any advice about this?
Yes I have  ` Forms9Patch.Droid.Settings.Initialize(this);` in the MainActivity in correct place.
btnInfo is a simple ImageButton from Xamarin.Forms standard.

**Comment by baskren** [comment]
@HTUlv412 -  

There isn't enough information here for me to be helpful.  Please share with me a small VisualStudio solution that demonstrates what you're seeing.  

- Ben

**Comment by baskren** [comment]
@HTUlv412 -

I really would like to help get to the bottom of this.  Could you send me a small demo app?

- Ben

**Comment by baskren** [comment]
No demo app, can't replicate.  Assuming dev error until a demo app can be provided.
