### ISSUE TITLE
UIWebView is obsolete, replace it with WKWebView

### ISSUE THREAD

**Issue by HTUlv412** [baskren/Forms9Patch#32]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by HTUlv412** [comment]
I hope you guys take a look of this, this is an amazing library and I use it in my projects as basics, I don't want to see it die.

**Comment by baskren** [comment]
@HTUlv412 -  This is fixed on the BetterDispose branch. Will be pushing an update later this week.
