### ISSUE TITLE
RgPopupWindow on iOS same native name error

### ISSUE THREAD

**Issue by ianvink** [baskren/Forms9Patch#33]
Hello,

A wonderful tool, thank you.

When I upgraded to 2.0.0 from 1.8.1 I get this error, even after a clean of obj and bin. Only on a real device though. The simulator works fine.

Reverting to 1.8.1 resolves the issue.

**Rg.Plugins.Popup.IOS' and 'Forms9Patch.iOS.PopupWindow, Forms9Patch.iOS') with the same native name ('RgPopupWindow')**

**Comment by baskren** [comment]
Just pushed 2.0.1.  I believe it should have the issue fixed but please verify.  If 2.0.1 doesn't fix it, as a work around (if you don't need it elsewhere), you can try removing Rg.Plugins.Popup package from all of your projects.

**Comment by baskren** [comment]
@ianvink 

Haven't heard back from you in a couple of weeks.  I'm assuming that means things are good?   Let me know.

**Comment by ianvink** [comment]
All good now
