### ISSUE TITLE
Forms9Patch Frame has extra padding on bottom compared to normal Frame

### ISSUE THREAD

**Issue by renzska** [baskren/Forms9Patch#34]
I updated to the latest version of Forms9Patch, 2.0.2, and am running into an issue where the Forms9Patch.Frame control is adding extra padding to the control on the bottom. Here are two screenshots that show the issue with the bottom Frame being the normal Xamarin Frame. I've also attached a sample project. I'm using the frame as a chat bubble and the extra padding is a problem.

![Simulator Screen Shot - iPhone 8 - 2019-11-19 at 01 09 07](https://user-images.githubusercontent.com/13021263/69128392-704a9000-0a69-11ea-9b55-d33cd295b2b0.png)

![Simulator Screen Shot - iPhone 8 - 2019-11-19 at 01 08 38](https://user-images.githubusercontent.com/13021263/69128411-7a6c8e80-0a69-11ea-94ce-13244a1ad4b7.png)

[frameissue.zip](https://github.com/baskren/Forms9Patch/files/3862630/frameissue.zip)

**Comment by baskren** [comment]
John -

Before I dive into this …. is the HasShadow property set to false?

- Ben
Ben Askren
BuildCalc developer
ben@buildcalc.com

 <http://buildcalc.com/>
 <http://buildcalc.com/>

**Comment by renzska** [comment]
I don’t set it so it would be whatever the default is. 

John

**Comment by baskren** [comment]
What happens if you set it to false?

Ben Askren
BuildCalc developer
ben@buildcalc.com

 <http://buildcalc.com/>
 <http://buildcalc.com/>

**Comment by renzska** [comment]
The padding is still there. See below:

``` <forms9patch:Frame
            BackgroundColor="Red" HasShadow="False">
           <forms9patch:Label Text="This is a sample"/>
        </forms9patch:Frame>
```

![Screen Shot 2019-11-20 at 9 22 38 AM](https://user-images.githubusercontent.com/13021263/69256950-7af34b00-0b77-11ea-86bf-85b482c6767c.png)



```
 <forms9patch:Frame
            BackgroundColor="Red" HasShadow="True">
           <forms9patch:Label Text="This is a sample"/>
        </forms9patch:Frame>
```

![Screen Shot 2019-11-20 at 9 24 12 AM](https://user-images.githubusercontent.com/13021263/69256988-8c3c5780-0b77-11ea-8873-38da6b7df9df.png)

**Comment by baskren** [comment]
Please send me a small demo app.

**Comment by renzska** [comment]
I had attached one to the initial commit. It’s the frameissue.zip attached to the initial issue message after the two images. Not very noticeable I now see.

John

**Comment by baskren** [comment]
Totally missed the zip!

OK, This is what I learned ... which may only demonstrate that I'm missing your point!

The padding in the sample app came from:
- The Xamarin.Forms.Frame
- The StackLayout.Spacing

I took your code and (1) changed the Xamarin.Forms.Frame to a Forms9Patch.Frame and (2) added a `Spacing="0"` argument to the `<StackLayout>` tag.  There is what I got:

![image](https://user-images.githubusercontent.com/2528888/69337435-d3395400-0c2e-11ea-92b3-afd059c75791.png)

Again, I'm guessing I'm missing your point because you have some decent Xamarin experience and I'm guessing you would have caught these.  So, that being said, please let me know what I've missed!

**Comment by renzska** [comment]
Let's see if I can explain it better using the actual application as the sample.

In this specific case I've been using the forms9patch frame as a bubble in a chat dialog. The same code has been used all along and I updated to the latest version. The latest version makes the bubble larger than the content inside of it; the space added below the text as seen when using v2.0.2. The extra grid code in the sample below is for an outgoing message to show up on the right 2/3 of the screen. I have the same code but starting at Column="1" for the incoming messages.

Basically, I'm trying to get it to render like it did with v1.4.0.3, without the extra space after the content. The label should be centered vertically within the content. I am currently unable to do that with the current forms9patch frame because it always has extra spacing inside the frame below the label.

Same Source Code for Both Versions:

```
  <forms9patch:Frame Grid.Row="1"
            Grid.Column="1"
            Grid.ColumnSpan="2"
            Margin="0,0,10,0"
            Padding="10,6,10,6"
            OutlineColor="Transparent"
            HasShadow="False"
            BackgroundColor="{StaticResource PrimaryColor}"
            OutlineRadius="10">
            <forms9patch:Label TextColor="White"
                HtmlText="{Binding HtmlFormattedMessage}"
                ActionTagTapped="Handle_ActionTagTapped" />
        </forms9patch:Frame>
```

The below screenshots are from the actual application using the forms9patch versions mentioned without changing any xaml.

> **Previous Form9Patch Version: 1.4.0.3**
> ![before](https://user-images.githubusercontent.com/13021263/69379365-980a4580-0c6d-11ea-93c3-9c36db10270f.png)




> **Current Form9Patch Version: 2.0.2**
> ![after](https://user-images.githubusercontent.com/13021263/69379378-9c366300-0c6d-11ea-98e3-8e4910c6b186.png)


Let me know if you need any more info or examples.

**Comment by renzska** [comment]
Looking at my initial post I realize it would have been helpful to show the actual xaml above each screenshot in addition to specify what I was hoping to achieve. Obviously, posting at 1am was a bad idea (under a crunch with this new version).

Thanks again for your time on this issue. I really appreciate it.

**Comment by baskren** [comment]
John -

I think I’ve found the root cause but, being what it is, I want to do a lot more testing before pushing an official release.  I’m almost out of battery to I’ll push a beta to NuGet.org <http://nuget.org/> in the morning so you can validate that it works for you.

Ben Askren
BuildCalc developer
ben@buildcalc.com

 <http://buildcalc.com/>
 <http://buildcalc.com/>

**Comment by baskren** [comment]
@renzska -

I've pushed v2.1.0-beta1 to NuGet.org.  To try it, you'll have to check the `Include prerelease` check box in the NuGet package manager in VisualStudio.

Note that I've already found a few things broken as a result of this "fix".  All but one is likely broken because I had been compensating for things not working correctly.  However, there's something going on with UWP with respect to 9patch backgrounds that has me a little worried.  I'll be looking into those things tomorrow.

**Comment by renzska** [comment]
Thanks for the update. I've tested the pre-release version and ran into some frame sizing issues with the following code:

```
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition
                Height="Auto">
            </RowDefinition>
        </Grid.RowDefinitions>
        <forms9patch:Frame Grid.ColumnSpan="3"
                           HasShadow="False"
                           BackgroundColor="#99242F">
            <Label TextColor="White"
                   Text="This is a test of the forms9patch frame" />
        </forms9patch:Frame>
    </Grid>
```

When I add an "s" to make the text say "frames" at the end it adds extra spacing to the bottom of the control. It's like it thinks the text has wrapped and is rendering it as such, even though it hasn't wrapped.

Here it is with "frame" at the end:
<img width="402" alt="Screen Shot 2019-11-25 at 8 58 08 AM" src="https://user-images.githubusercontent.com/13021263/69556659-5bd32f80-0f62-11ea-9177-fb2ea5487de0.png">

Here it is with "frames" at the end:
<img width="403" alt="Screen Shot 2019-11-25 at 8 58 51 AM" src="https://user-images.githubusercontent.com/13021263/69556673-642b6a80-0f62-11ea-8eda-786ef97bd90b.png">

**Comment by baskren** [comment]
John -

I think I saw this in my testing as well.  All the iOS and Android tests are now passing and I’m going to take a look at the UWP next.  Once they’re passing, I’ll share.


Ben Askren
BuildCalc developer
ben@buildcalc.com

 <http://buildcalc.com/>
 <http://buildcalc.com/>

**Comment by baskren** [comment]
OK, version 2.1.0 is now available on NuGet.org.  Let me know how it works for you!

**Comment by baskren** [comment]
@renzska - FYI: found a weird issue with Button text being clipped on iOS versions older than 11.3.  Version 2.1.1 address this and a number of bugs with the TargetedMenu popup.

**Comment by baskren** [comment]
@renzska 

John -  I know you're probably really busy.  I just wanted to check with you to see if 2.1.1 is meeting your expectations.

- Ben

**Comment by renzska** [comment]
@baskren 

I'm currently having our testers test out the new version and so far everything looks great. I'll let you know if we run into anything.

Thanks again for the quick turnaround on this.

**Comment by baskren** [comment]
@renzska -  
Thanks, John.
