### ISSUE TITLE
[Android Pie] Forms9Patch.Label AutoFit is not working well for Chinese words

### ISSUE THREAD

**Issue by ericc0504** [baskren/Forms9Patch#35]
I found that the auto size label is not working well on Android Pie. For English word, it works like a charm but if there is some Chinese words, the last line of words will be cropped.

<img width="400" alt="Screenshot 2019-12-02 at 18 44 02" src="https://user-images.githubusercontent.com/26959081/69953216-bd336980-1533-11ea-9716-70b91ec28221.png">

Configuration:
Forms9Patch: 2.1.2
Xamarin Forms: 4.3.0.991211
Emulator: Pixel 2 XL
Android OS: Pie (API 28)

Attached with the demo code: [WordCroppedDemo.zip](https://github.com/baskren/Forms9Patch/files/3910843/WordCroppedDemo.zip)

**Comment by baskren** [comment]
I'll take a look at this later this week.  In the mean time ... does it also do this in iOS and UWP?  My guess is not - which would be bad news.

**Comment by ericc0504** [comment]
It is quite strange that the issue doesn't occur in iOS and even Android 8.1 (API 27) but I didn't test it on UWP.

**Comment by baskren** [comment]
Bummer.  That is what I was afraid of. 

I do have some text rendering logic that changes when the API is >= Android.M (API 23) ...

https://github.com/baskren/Forms9Patch/blob/749ec888a0bb8677abe0d422b8df2285a3e751b2/Forms9Patch/Forms9Patch.Droid/Extensions/TextExtensions.cs#L51-L63

... but a quick repo search for `Android.OS.BuildVersionCodes.` yielded nothing.  Which means the Forms9Patch code is the same between API 27 and API 28.  

Again, I'll take a look later this week.  Right now, it's a toss up as to if it's a Forms9Patch bug or something less actionable.

**Comment by ericc0504** [comment]
Hi @baskren. Is there any possible fix or work around for the issue?

**Comment by baskren** [comment]
@ericc0504 

I hope to be proven wrong - if I understand it correctly, the root cause is in the Android StaticLayout.Builder.  

That being said, if I were in your shoes, I might consider breaking the string into separate labels based upon character set.  Not an enviable task.

**Comment by ericc0504** [comment]
Besides, I have noticed that the auto fit label will be rendered correctly without putting in a StackLayout like the following:
```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             xmlns:Forms9Patch="clr-namespace:Forms9Patch;assembly=Forms9Patch"
             x:Class="WordCroppedDemo.MainPage">
       <Forms9Patch:Label x:Name="ChiStrLabel" Lines="3" AutoFit="Width"/>
</ContentPage>
```
Does it give any inspiration?

**Comment by baskren** [comment]
@ericc0504  

My apologies, I misunderstood the symptoms you were trying to describe.  I'm taking a look now.

**Comment by baskren** [comment]
Definitely an Android issue:  https://github.com/facebook/react-native/issues/24837

**Comment by ericc0504** [comment]
Thanks for verifying the issue. A work around mentioned in facebook/react-native#24837 is to set the "targetSdkVersion" to "27" but it is no longer working since Google Play Store is no long accept an app targeting below API 28.

**Comment by baskren** [comment]
Thanks for your patience with this.  I've implemented a solution in the source code and, once I've addressed an issue in UWP, I'll be pushing version 2.2.

**Comment by ericc0504** [comment]
It's definitely a good news! Hope to see the release soon 👍

**Comment by baskren** [comment]
Version 2.2 is now available with this fixed.
