### ISSUE TITLE
Object not dispose in ListView  RecycleViewElement  (NativeGestureDetector.Dispose )

### ISSUE THREAD

**Issue by manicoder** [baskren/Forms9Patch#4]
NativeGestureDetector.Dispose (System.Boolean disposing)
C:\Users\ben\Development\Forms9Patch2\FormsGestures\FormsGestures.Source.Droid\Detectors\NativeGestureDetector.cs, line 27
System.Exception: Cannot access a disposed object. Object name: 'FormsGestures.Droid.NativeGestureDetector'.

**Comment by manicoder** [comment]
issue occurred after upgrading package v1.6.5.1
Now going to downgrade with previous version.

**Comment by baskren** [comment]
Can you send a sample project that demonstrates this issue?

**Comment by baskren** [comment]
Without a sample project that demonstrates this issue, there is nothing actionable.  Closing issue until a sample project is available.
