### ISSUE TITLE
Latest Version giving Issues on UWP and Android

### ISSUE THREAD

**Issue by KatruM** [baskren/Forms9Patch#42]
![image](https://user-images.githubusercontent.com/47590113/73461859-decc9800-43a0-11ea-8b7a-c5642c20f3e2.png)

Could you please help me on this issue ??

**Comment by baskren** [comment]
There is not enough information here to know a fraction of what is needed to diagnose this issue.  Please send me a small demo project that replicates this issue and I will be happy to look at this for you.

**Comment by KatruM** [comment]
Thanks for the Reply.
Here is the sample. When i used this across the platforms it gives me error in the Android and UWP Projects. FYI
![image](https://user-images.githubusercontent.com/47590113/73562490-3fcb9d00-4481-11ea-9657-1a75d8ed3bc9.png)
[Forms9PatchLabelIssue.zip](https://github.com/baskren/Forms9Patch/files/4140714/Forms9PatchLabelIssue.zip)

Please help me on this.

Thanks

**Comment by KatruM** [comment]
I was Able to fix the Above issue but i am running in to another issue in release mode the content is not showing and debug mode it is showing .
Please let me know what i am missing.

**Comment by baskren** [comment]
OK, @KatruM -

Please read the [Getting Started Guide](https://baskren.github.io/Forms9Patch/guides/GettingStartedWindows.html) - specifically step 6.  In the sample solution you provided, all three of your platform projects are missing the Forms9Patch initialization code.   Besides being very unstable, this will also give the symptoms you are seeing as the linker will remove all Forms9Patch platform renderers without something (the Forms9Patch initialization code) telling it not to.  

For the same reason, this is why Xamarin.Forms has initialization code in the platform projects as does Xamarin.Essentials and pretty much any project that makes use of platform specific code.

Having made mistakes like this myself all too often, I'm guessing there is a chance that forgetting to put the initialization code into the sample solution was an accident and there is some other problem with the solution that prompted you to contact me.  Once you try adding the proper initialization code and test, let me know if you still have an issue.

- Ben

**Comment by KatruM** [comment]
Thanks will check and let you know

**Comment by baskren** [comment]
@KatruM ... any news?

**Comment by plexxis-htarwala** [comment]
Hi I am still getting the errors in UWP. Please see below link containing a sample project with the issue. Using Form9patch v2.2.4. XF4.5

https://file.io/RDCpNJ

Thanks.

**Comment by plexxis-htarwala** [comment]
Note it really does not matter if initialization code is added or not. Simply adding the package results in error. No change even after adding the initialization and recompiling the project.

**Comment by baskren** [comment]
@ht20200101 - please give version 2.2.5 a try.  It addressed the UWP build issues present in version 2.2.4.
