### ISSUE TITLE
Expand FlyoutPopup to full page

### ISSUE THREAD

**Issue by GW-FUB** [baskren/Forms9Patch#44]
I want to fill the full page with the flyout popup. Unfortunately it stops expanding after about 1/3 of the page when flying in from top or bottom.

![example](https://user-images.githubusercontent.com/23636756/75781214-18f0d700-5d5d-11ea-89dc-f1c50dc820ca.png)

Is it possible to remove this restriction and to expand it to the whole page?

I want to achive something like this: (Popup over page, some free space over the header on top)
![grafik](https://user-images.githubusercontent.com/23636756/75781600-cb289e80-5d5d-11ea-9d53-302779374d01.png)

**Comment by GW-FUB** [comment]
Figured it out by myself. Just use a ModalPopup and set the animation property. Then it behaves like I wanted.

**Comment by GW-FUB** [comment]
Ok, next problem: 
When I use the modal popup for this, it appears for one frame or so on the screen before the animation begins. So it flickers just a very short time, disapears and then comes in from the bottom. Unfortunately it's not possible to inherit from your Base PopupPage, because it's internal (Why?).

Is there a better base popup that I can use for this? Or a way to prevent the flickering?

**Comment by GW-FUB** [comment]
Found a hack to prevent the flickering:

First set the default location to something totally outside of the screen:
`Location = new Point(10000, 10000);`

Override the OnAppearing method and change the location back to default at the end:
`Location = new Point(double.NegativeInfinity, double.NegativeInfinity);`

Now there is no flickering anymore :-)

**Comment by baskren** [comment]
@GW-FUB 

Thanks for taking the time to document your journey!  You ROCK!
