### ISSUE TITLE
Forms9Patch.Label doesn't work in Android previewer

### ISSUE THREAD

**Issue by Qythyx** [baskren/Forms9Patch#50]
It works fine in iOS previewer, but in Android it says `There was a problem creating an instance of Forms9Patch.Label in the Previewer, so it was replaced by Xamarin.Forms.Label.` If I look at more details it says, `System.TypeInitializationException was thrown. The type initializer for 'Forms9Patch.Label' thew an exception.` Unfortunately I can't see much details about the stack, but what is shown is:
`<unknown method>`
`System.Reflection.RuntimConstructorInfo.InternalInvoke (System.Object obj,`

**Comment by baskren** [comment]
1. Can you share with me a test project that demonstrates this issue?
2. Did you add `Forms9Patch.Droid.Settings.Initialize(this);` to you Android project's MainActivity.cs?

**Comment by baskren** [comment]
@Qythyx -

Since I haven't heard back from you for over a month, I'm going to close this issue.
