### ISSUE TITLE
Feature Request : To PNG/To JPG on all layout types

### ISSUE THREAD

**Issue by chrisfoulds** [baskren/Forms9Patch#51]
Would it be possible to add the feature of to PNG/to JPG on all layout types.
So for example I could save the render of an entire Stacklayout as an image ?

**Comment by baskren** [comment]
There is already a library that does a pretty good job of this (except it is generating PDFs): [PDFSharp.Xamarin.Forms](https://github.com/akgulebubekir/PDFSharp.Xamarin.Forms).   Once you are familiar with this library, you'll see it's a trivial effort to build a feature like this.
