### ISSUE TITLE
More complex SVGs are malformed

### ISSUE THREAD

**Issue by matibak** [baskren/Forms9Patch#52]
Some SVGs ale not drawn properly. You can compare [here](https://github.com/matibak/XamarinSvgTest) how `Forms9Patch` draws some SVGs in comparison to `FFImageLoading` and `SkiaSharp.SVG`. What would we need to do to draw SVGs properly?

**Comment by baskren** [comment]
@matibak -

I could not get your project to run.

Android: 
![image](https://user-images.githubusercontent.com/2528888/85573111-98076500-b603-11ea-90bc-300c9331444c.png)

iOS: 
- not all of the SvgTest.Resources were set as EmbeddedResources.  
- once the above was fixed, getting the following exception:

![image](https://user-images.githubusercontent.com/2528888/85573016-802fe100-b603-11ea-97f3-9a910fdc8900.png)


Also, I should note that it's quite surprising you are able to get different results using SkiaSharp.SVG.  That is the renderer Forms9Patch uses for SVG images.

**Comment by baskren** [comment]
@matibak 

It's a long story but, FWIW, I've recently noticed (https://github.com/baskren/AssetBuilder) some SVG files don't render correctly when using SkiaSharp.SVG.  Could that be what you are referring to?

**Comment by baskren** [comment]
@matibak -

Since I haven't heard back from you for over a month, I'm going to close this issue.
