### ISSUE TITLE
Button has no separate size parameter for the icon

### ISSUE THREAD

**Issue by chrisfoulds** [baskren/Forms9Patch#55]
Whilst I can specify the overall font size I can't specify the size of the icon when using an IconFontFamily meaning I don't have full UI control over this element.

**Comment by baskren** [comment]
@chrisfoulds -

To the master branch, I've just added `IconFontSize` to all button elements and overridable by segment and menu item.  Additionally, `IconFontFamily` is now also and overridable by segment and menu item;

I should be releasing a new NuGet later today.

**Comment by chrisfoulds** [comment]
Awesome, thank you

**Comment by baskren** [comment]
Version 2.3 has been released.  Please let me know if this does not fix this issue.

**Comment by chrisfoulds** [comment]
Works a treat, thank you
