### ISSUE TITLE
Java.Lang.UnsupportedOperationException on WearOS...

### ISSUE THREAD

**Issue by dimitrijevic** [baskren/Forms9Patch#59]
Great work and nuget first...but trying to run it on an Asus ZenWatch 2 (API 25 compatible i.e. 7.1) device one gets `Java.Lang.UnsupportedOperationException: ''` upon 
`Forms9Patch.Droid.Settings.Initialize(this);` while the same code runs on an API 23 i.e. Android 6.0 phone...is there something doing it wrong or devices like WearOS smartwatches just can't run it please as this would be the main reason I'd like to use it commercially?

**Comment by baskren** [comment]
At the moment, I have no plans of supporting WearOS.  If WearOS support is valuable to you, please consider a [Sponsorship](https://github.com/sponsors/baskren).
