### ISSUE TITLE
Label cutoff [Android]

### ISSUE THREAD

**Issue by jvhgamer** [baskren/Forms9Patch#6]
[Sample image](https://i.ibb.co/Pjs9tWH/sample.jpg) (black boxes for reference of item1 and item2).
Full text: SAMPLE TEXT ENTRY.

Label is being cutoff with the following settings:

```
lblTest = new Forms9Patch.Label
{
    Text = "textSet@Runtime",
    TextColor = Color.Black,
    BackgroundColor = Color.Transparent,
    HorizontalOptions = LayoutOptions.FillAndExpand,
    VerticalOptions = LayoutOptions.Center,
    FontSize = 40,
    Lines = 1,
    AutoFit = Forms9Patch.AutoFit.Width,
};
```

Inside of parent...

```
gridTest = new Grid
{
    RowDefinitions =
    {
        new RowDefinition { Height = new GridLength(1, GridUnitType.Star) },
    },
    ColumnDefinitions =
    {
        new ColumnDefinition { Width = new GridLength(1, GridUnitType.Auto) },
        new ColumnDefinition { Width = new GridLength(10, GridUnitType.Star) },
        new ColumnDefinition { Width = new GridLength(2, GridUnitType.Auto) },
    },
    HorizontalOptions = LayoutOptions.FillAndExpand,
    VerticalOptions = LayoutOptions.Start,
    BackgroundColor = Color.White,
    Padding = new Thickness(10, 0),
};
gridTest.Children.Add(item1, 0, 0);
gridTest.Children.Add(lblTest, 1, 0);
gridTest.Children.Add(item2, 2, 0);
```

Cutoff only occurring on Android. iOS appears fine.

**Comment by jvhgamer** [comment]
Reverted to using `Xamarin.Forms.Label` on `Android` per this cut-off. Unsure how to fix.

**Comment by baskren** [comment]
@jvhgamer:  I just uploaded 1.6.6.2 to address an issue that sounds a lot like the one you are seeing.  Please give it a try and let me know if your issue persists.  If it does, please provide me a sample project via a github repo that demonstrates the issue.  The code sample you provided is not sufficient to determine the root cause.

**Comment by jvhgamer** [comment]
> @jvhgamer: I just uploaded 1.6.6.2 to address an issue that sounds a lot like the one you are seeing. Please give it a try and let me know if your issue persists. If it does, please provide me a sample project via a github repo that demonstrates the issue. The code sample you provided is not sufficient to determine the root cause.

[Sample project via github repo](https://github.com/jvhgamer/Forms9Sample)

**Comment by baskren** [comment]
Jack -

I just downloaded your app and ran it.  Attached is a gif of what I saw.  What is wrong with what I’m seeing?

https://1drv.ms/u/s!AkPAsLOJX3DCikXNzgjpz5M3Gw5Q


Ben Askren
BuildCalc developer
ben@buildcalc.com

 <http://buildcalc.com/>
 <http://buildcalc.com/>

**Comment by jvhgamer** [comment]
@baskren Did you make any changes? [Here's](https://we.tl/t-Pd0f5ds9g3) what I'm seeing. The end of the label is cutoff as if by a margin

**Comment by baskren** [comment]
zero changes.  Loaded it up and ran it.  

Ben Askren
BuildCalc developer
ben@buildcalc.com

 <http://buildcalc.com/>
 <http://buildcalc.com/>

**Comment by baskren** [comment]
@jvhgamer What happens when you run it on the emulator?

**Comment by baskren** [comment]
@jvhgamer What happens when you replace the two images with BoxView { Color = Color.Black } ?

**Comment by jvhgamer** [comment]
@baskren how is it possible the same solution, untouched, shows different results? I'm running this on a Galaxy S9+. Could this be a device specific issue? Perhaps a setting within the device settings?

**Comment by jvhgamer** [comment]
@baskren Works perfectly on the emulator. What could this setting be? I'm not familiar with Android

**Comment by baskren** [comment]
Your hypothesis about it being a device specific issue could be the root cause.  Thank you for letting me know you were testing on a Galaxy S9+.  I’ll look up the specs to see if I can build an emulator with the same properties (I would recommend you try it too).  That might lead me to the offending code.


Ben Askren
BuildCalc developer
ben@buildcalc.com

 <http://buildcalc.com/>
 <http://buildcalc.com/>

**Comment by jvhgamer** [comment]
Will do. Adding the Galaxy S9+ skin via Android AVD is not working but I will test based on device specs, at the least.

**Comment by baskren** [comment]
@jvhgamer 

I just built an emulator to the same specs as the Galaxy S9+ (1440x2690, 529dpi).  I could not replicate the issue you are seeing.

**Comment by baskren** [comment]
@jvhgamer 

I think I figured out what's happening.  In Settings / Display / Advanced / Font Size and return the font size to "Default".  You should see things work as they should.

Now I need to see what I'm doing wrong!

**Comment by jvhgamer** [comment]
Yes indeed that was it. Two things: the path as it unfolded on my physical device (GS9+) - Settings -> Display -> Font and screen zoom -> FONT SIZE. On this device there are seven (7) notches ranging from Tiny to Huge. Previously the notch was set to four (4), the very middle of this range. Setting the notch to three (3), or one below the middle line, addresses the bug.

**Comment by jvhgamer** [comment]
@baskren Can't say I know much if anything about restricting these font size adjustments but a possible solution might be to enforce the app's text as this default. Could this prevent users font size settings from altering the app layout?

**Comment by jvhgamer** [comment]
Device specific [solution](https://stackoverflow.com/questions/49649874/how-to-prevent-device-font-size-effect-of-xamarin-android-app). I'll see about an iOS equivalency..

**Comment by jvhgamer** [comment]
@baskren Can't say I know much if anything about restricting these font size adjustments but a possible solution might be to enforce the app's text as this default. Could this prevent users font size settings from altering the app layout? [Android solution](https://stackoverflow.com/questions/49649874/how-to-prevent-device-font-size-effect-of-xamarin-android-app). Having trouble finding an iOS equivalent

**Comment by baskren** [comment]
@jvhgamer 

I just uploaded v1.6.7 to Nuget.org.  It addresses the root cause of this issue.  With this version, you should be able to change the System FontSize without causes Forms9Patch.Label's autofit algorithms to fail.
