### ISSUE TITLE
Forms9Patch.Button throw exception on ios

### ISSUE THREAD

**Issue by saeede29** [baskren/Forms9Patch#60]
hi,

I am trying to use Forms9Patch.WebViewPrintEffect , I have added Forms9Patch into my project , 
I have followed this tutorial:
https://medium.com/@ben_12456/share-xamarin-forms-webview-as-a-pdf-a877542e824a

I am able to get the app run in android simulator it works just fine however when I try to run it on iphone simulator I get error  :
        System.TypeInitializationException has been thrown:

     The type initializer for 'Forms9Patch.Button' threw an exception.
not really sure whats going on.
Thanks

**Comment by baskren** [comment]
Not sure myself.  First, what is going on in your iOS AppDelegate.cs file?  Did you add:
```
Forms9Patch.iOS.Settings.Initialize(this);
```

**Comment by baskren** [comment]
@saeede29 -

Can you share with me a demo project that replicates the issue you are seeing?  I cannot replicate.

- Ben

**Comment by saeede29** [comment]
@baskren  thank u so much Forms9Patch.iOS.Settings.Initialize(this); was the issue. I added that and it was settle.
