### ISSUE TITLE
[Bug] Button disappears when it should be disabled

### ISSUE THREAD

**Issue by michaelfoster9** [baskren/Forms9Patch#61]
### Description
Hello, I am using your ftp:Button class. Essentially, I want to use it because the normal button doesn't trigger the IsEnabled trigger correctly.

I prefer to use your Button class instead of the StateButton class. Your documentation recommends that and it's easier to use anyways.

However, when you bind the button's Command to a command that supports CanExecute, the f9p:Button becomes invisible when CanExecute=false and I think it should be disabled.  In comparison, the StateButton is properly disabled when CanExecute=false.

**Comment by baskren** [comment]
Can you send me a small sample project that demonstrates this?  I’m not 100% sure I can picture what you are trying to share with me.

**Comment by michaelfoster9** [comment]
Hello, it would be difficult for me to package up my app removing all of the dependencies but below you can see the code for two buttons, one is a regular button and the other is the State Button

`
                    <f9p:Button Text="Add To Playlist" Command="{Binding AddToPlaylistCommand}" TextColor="White" ImageSource="{local:ImageMultiResource CompanionForSpotifyForms.Resources.ic_refresh_white_24dp}" />
                    
                    <f9p:StateButton Command="{Binding AddToPlaylistCommand}">
                        <f9p:StateButton.DefaultState>
                            <f9p:ButtonState Text="Add To Playlist" Orientation="Vertical">
                                <f9p:ButtonState.IconImage>
                                    <f9p:Image Source="{local:ImageMultiResource CompanionForSpotifyForms.Resources.ic_refresh_white_24dp}"/>
                                </f9p:ButtonState.IconImage>
                            </f9p:ButtonState>
                        </f9p:StateButton.DefaultState>
                    </f9p:StateButton>
`

Both of those buttons bind to a Command object on the ViewModel. The Command is implemented as such where the second delegate is a function that determines if the Command CanExecute or not.  

`
            AddToPlaylistCommand = new DelegateCommand(async () =>
            {
                await AddToPlaylist();
            }, () => HasTracks);
`

When HasTracks=False, the StateButton displays in a Disabled state. That is the  correct behavior.  However, the regular button becomes hidden which is not the correct behavior (in my opinion)

**Comment by baskren** [comment]
@michaelfoster9 

I tried using the code you shared but quickly realized there is just too much stuff missing to be able to diagnose what may be happening here.  Again, a small, sample project goes a long way to making it possible to find the root cause of an issue.

**Comment by baskren** [comment]
@michaelfoster9 

Another big reason why I would like to see a sample project.  Looking at the source code, it's not obvious how Button could be invisible as a result of the change in its ability to execute a command:

```
        /// <summary>
        /// Backing store for the Button.CommandParameter bindable property.
        /// </summary>
        public static readonly BindableProperty CommandParameterProperty = BindableProperty.Create(nameof(CommandParameter), typeof(object), typeof(Button), null, BindingMode.OneWay, null,
            new BindableProperty.BindingPropertyChangedDelegate((bo, o, n) =>
                ((Button)bo).CommandCanExecuteChanged(bo, EventArgs.Empty)),
             null, null, null);
```

```
        void OnCommandChanged()
        {
            if (Command != null)
            {
                Command.CanExecuteChanged += CommandCanExecuteChanged;
                CommandCanExecuteChanged(this, EventArgs.Empty);
            }
            else
                IsEnabledCore = true;
        }

        void OnCommandChanged()
        {
            if (Command != null)
            {
                Command.CanExecuteChanged += CommandCanExecuteChanged;
                CommandCanExecuteChanged(this, EventArgs.Empty);
            }
            else
                IsEnabledCore = true;
        }

        void CommandCanExecuteChanged(object sender, EventArgs eventArgs)
            => IsEnabledCore = (Command?.CanExecute(CommandParameter) ?? IsEnabled);

```

And the declaration of `IsEnabledCore`:

```
        bool IsEnabledCore
        {
            set => SetValue(IsEnabledProperty, value);
        }
```

`IsEnabledCore` is a property of `Xamarin.Forms.VisualElement` - so in other words, Forms9Patch.Button is passing off the enable/disable state to Xamarin.Forms.

Which brings me to a very interesting point:  `Forms9Patch.StateButton` is derived from `Forms9Patch.Button`.  In the case of `Command`, `CommandParameter`, and `CanExecuteChanged`, all of the function is managed by the code in `Forms9Patch.Button`.   So now, I'm really intrigued about what you are seeing as it appears to be multiple types of wrong behavior on multiple from multiple elements.

So again, **please** share with me a demo project.  It would be greatly appreciated.

**Comment by michaelfoster9** [comment]
Ben, I attached a sample to an email.

**Comment by michaelfoster9** [comment]
Ben, attached is a s ample and I have some more info. It turns out the button is NOT hidden. but, the problem one occurs in a Dark Theme where the background is black and the text is white.

In that case, if you disable the buttons a disabled f9p:Button will set the text color to black and thus appear invisible where a disabled f9P:StateButton will set the text color to grey and you can see the button.

This can be demonstrated in the linked app below

https://www.dropbox.com/s/3xmb3v5jjyapi5q/ButtonBindingSample.zip?dl=0

**Comment by baskren** [comment]
Very helpful.  I should be able to take a look at this in the morning.

**Comment by michaelfoster9** [comment]
Thanks, I thought I could fix it with a style as follows but the IsEnabled=False trigger never seems to kick in

`        <Style x:Key="ToolbarButton2" TargetType="f9p:Button">
            <Style.Triggers>
                <Trigger TargetType="f9p:Button"  Property="IsEnabled"  Value="True">
                    <Setter Property="BackgroundColor" Value="Transparent" />
                    <Setter Property="TextColor" Value="White" />
                    <Setter Property="Opacity" Value="1" />
                </Trigger>
                <Trigger TargetType="f9p:Button"  Property="IsEnabled"  Value="False">
                    <Setter Property="BackgroundColor" Value="Transparent" />
                    <Setter Property="TextColor" Value="LightGray" />
                    <Setter Property="Opacity" Value="0.5" />
                </Trigger>
            </Style.Triggers>
        </Style>
`

**Comment by baskren** [comment]
That's more good information.

**Comment by baskren** [comment]
@michaelfoster9 

Thank you for sharing with me the demo project.  Again, it is amazing how much easier it is to communicate an issue when such a project is provided.

For the sake of documenting this for others, below is an excerpt of the email in which you shared the demo project:

> It turns out the button is NOT hidden. but, the problem one occurs in a Dark Theme where the background is black and the text is white.
>
>In that case, if you disable the buttons a disabled f9p:Button will set the text color to black and thus appear invisible where a disabled f9P:StateButton will set the text color to grey and you can see the button.

For reference, here is the demo project's XAML:

### MainPage.xaml
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:f9p="clr-namespace:Forms9Patch;assembly=Forms9Patch"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="ButtonBindingSample.MainPage">

    <StackLayout>
        <f9p:Button Text="Simple Button" TextColor="White" Command="{Binding CommandWithDisabledState}"/>
        <f9p:StateButton Text="State Button" TextColor="White" Command="{Binding CommandWithDisabledState}"/>
        <f9p:Button Text="Toggle State" TextColor="White" Command="{Binding ToggleCommand}"/>
    </StackLayout>

</ContentPage>
```
### MainPage.xaml.cs
``` csharp
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Input;
using Xamarin.Forms;

namespace ButtonBindingSample
{
    // Learn more about making custom code visible in the Xamarin.Forms previewer
    // by visiting https://aka.ms/xamarinforms-previewer
    [DesignTimeVisible(false)]
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            BindingContext = new ViewModel();
        }
    }

    public class ViewModel
    {
        public ViewModel()
        {

            CommandWithDisabledState = new DelegateCommand(
                () => { }, 
                () => { return _toggle; });

            ToggleCommand = new DelegateCommand(
                () => {
                    _toggle = !_toggle;
                    CommandWithDisabledState.RaiseCanExecuteChanged();
                });
        }

        private bool _toggle = false;

        public DelegateCommand CommandWithDisabledState { get; }
        public DelegateCommand ToggleCommand { get; }
        public string Text => "Hello world";
    }


    public class DelegateCommand : ICommand
    {
        /// <summary>
        /// The _execute
        /// </summary>
        private readonly Action _execute;

        /// <summary>
        /// The _can execute
        /// </summary>
        private readonly Func<bool> _canExecute;

        /// <summary>
        /// Initializes a new instance of the <see cref="DelegateCommand"/> class.
        /// </summary>
        /// <param name="execute">The execute.</param>
        /// <param name="canExecute">The can execute.</param>
        /// <exception cref="System.ArgumentNullException">execute</exception>
        public DelegateCommand(Action execute, Func<bool> canExecute)
        {
            _execute = execute ?? throw new ArgumentNullException("execute");

            if (canExecute != null)
            {
                this._canExecute = canExecute;
            }
        }

        /// <summary>
        /// Initializes a new instance of the DelegateCommand class that
        /// can always execute.
        /// </summary>
        /// <param name="execute">The execution logic.</param>
        /// <exception cref="ArgumentNullException">If the execute argument is null.</exception>
        public DelegateCommand(Action execute)
            : this(execute, null)
        {
        }

        /// <summary>
        /// Occurs when changes occur that affect whether the command should execute.
        /// </summary>
        public event EventHandler CanExecuteChanged;


        /// <summary>
        /// Raises the can execute changed.
        /// </summary>
        public void RaiseCanExecuteChanged()
        {

            CanExecuteChanged?.Invoke(this, EventArgs.Empty);
        }

        /// <summary>
        /// Defines the method that determines whether the command can execute in its current state.
        /// </summary>
        /// <param name="parameter">Data used by the command.  If the command does not require data to be passed, this object can be set to null.</param>
        /// <returns>true if this command can be executed; otherwise, false.</returns>
        public bool CanExecute(object parameter)
        {
            return _canExecute == null || _canExecute.Invoke();
        }

        /// <summary>
        /// Defines the method to be called when the command is invoked.
        /// </summary>
        /// <param name="parameter">Data used by the command.  If the command does not require data to be passed, this object can be set to null.</param>
        public virtual void Execute(object parameter)
        {
            if (CanExecute(parameter))
            {
                _execute.Invoke();
            }
        }
    }

}

```

Which produces the following screen shot (in light mode):
<img width="467" alt="image" src="https://user-images.githubusercontent.com/2528888/87036945-86a08a00-c1b9-11ea-9ebd-1eab6f7a4051.png">

And this screen shot (in dark mode):
<img width="467" alt="image" src="https://user-images.githubusercontent.com/2528888/87037166-cff0d980-c1b9-11ea-8497-a032273e02f5.png">

Which, except for the navigation bar, is pretty much the same screen shot.  So, to see what's going on, I'm going to make two changes:
1. Set the background color to red.
2. Add a Xamarin.Forms.Button to the list of buttons, so we can compare the Forms9Patch buttons to its behavior.

Here is the resulting screen shot (light mode  vs dark mode):
<img width="467" alt="image" src="https://user-images.githubusercontent.com/2528888/87037516-55748980-c1ba-11ea-90da-397b533b4a7c.png"><img width="467" alt="image" src="https://user-images.githubusercontent.com/2528888/87037437-35dd6100-c1ba-11ea-84d0-4d886951145d.png">

And here are the two screen shots (light vs dark), after the [Toggle State] button has been tapped:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/2528888/87037662-9371ad80-c1ba-11ea-8fe6-498f051d38a1.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/2528888/87037711-a97f6e00-c1ba-11ea-8fa0-62a71ba72e17.png">

So, first notice that Forms9Patch.Button and Xamarin.Forms.Button pretty much behave the same.  It's Forms9Patch.StateButton that is different.  Why is that?  Because Forms9Patch.StateButton apples the property values from its DefaultState to all other states, unless otherwise specified.  In other words, the values you set for the StateButton's properties (in your XAML) are the DefaultState properties.  And, because you didn't specify any property values for any other states, the StateButton remains unchanged between the enabled and disabled state.  

If you wanted the Forms9Patch.StateButton to behave like the other buttons, you would specify more state information.  Here is what I did:
``` xaml
        <f9p:StateButton Text="State Button" TextColor="White" Command="{Binding CommandWithDisabledState}">
            <f9p:StateButton.DisabledState >
                <f9p:ButtonState TextColor="#4FFF" Text="StateButton - Disabled" />
            </f9p:StateButton.DisabledState>
        </f9p:StateButton>
```

Which, in turn, gives the following screen shots (disabled vs enabled):
#### Dark Mode:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/2528888/87038600-fa439680-c1bb-11ea-84de-e4e99734e0e1.png"> <img width="434" alt="image" src="https://user-images.githubusercontent.com/2528888/87038617-016aa480-c1bc-11ea-87c4-859d8849da3d.png">

#### Light Mode:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/2528888/87038512-da13d780-c1bb-11ea-9e2d-5d96599275f4.png"> <img width="434" alt="image" src="https://user-images.githubusercontent.com/2528888/87038536-e13ae580-c1bb-11ea-9f3f-099a02002fd1.png">

So, now you can see that all the buttons behavior is (almost) identical.  

I'm not 100% sure this answers your question, so there is one more thing worth talking about: [Xamarin.Forms Visual State Manager](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager).  I'm not going to go into how to use it here but, effectively, it is a much more general (and useful) way of accomplishing what I intended to do with StateButton and its states.  Thus, you can use the Visual State Manager to get Forms9Patch.Button and Xamarin.Forms.Button to do what Forms9Patch.StateButton can do - finely control the button's properties as a function of state.

And one more time, I may have misunderstood your question, answered the wrong question, or given a less than helpful answer.  If any of these are the case, please let me know where I went astray so I can get you what you need to get up and going.

**Comment by michaelfoster9** [comment]
@baskren thanks for looking in to this! I will digest this much more later when i have more time. in the mean time though, can you try this with the UWP dark mode theme, which is where I think i saw this. 

like I said, i'll try to digest this more thoroughly this evening!!

**Comment by michaelfoster9** [comment]
If you make the background of the page black, as shown below, you can see the problem. 
Both the State Button and the Simple button have white text. However, when you disable them by clicking Toggle State, State Button gets Grey text and looks "disabled". The Simple Button text becomes basically black and the button looks invisible. So, the two buttons look very different when in a disabled state.   An alternative to a fix would be if I could control the background color and text color of the F9p:Button when in a disabled state via Triggers.

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:f9p="clr-namespace:Forms9Patch;assembly=Forms9Patch"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             BackgroundColor="Black"
             x:Class="ButtonBindingSample.MainPage">

    <StackLayout>
        <f9p:Button Text="Simple Button" TextColor="White" Command="{Binding CommandWithDisabledState}"/>
        <f9p:StateButton Text="State Button" TextColor="White" Command="{Binding CommandWithDisabledState}"/>
        <f9p:Button Text="Toggle State" TextColor="White" Command="{Binding ToggleCommand}"/>
    </StackLayout>

</ContentPage>
`

**Comment by baskren** [comment]
@michaelfoster9 

Thanks for continuing to prod me along with this.  I still am struggling to see what is wrong.  For example:

``` xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:f9p="clr-namespace:Forms9Patch;assembly=Forms9Patch"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="ButtonBindingSample.MainPage"
             Padding="10"
             BackgroundColor="Green"
             >

    <StackLayout>
        <f9p:Button Text="Simple Button" TextColor="White" Command="{Binding CommandWithDisabledState}"/>
        <f9p:StateButton Text="State Button" TextColor="White" Command="{Binding CommandWithDisabledState}">
            <f9p:StateButton.DisabledState >
                <f9p:ButtonState TextColor="#4000" Text="StateButton - Disabled" />
            </f9p:StateButton.DisabledState>
        </f9p:StateButton>
        <Button Text="Xamarin Button" TextColor="White" Command="{Binding CommandWithDisabledState}"/>
        <f9p:Button Text="Toggle State" TextColor="White" DarkTheme="True" Command="{Binding ToggleCommand}"/>
    </StackLayout>

</ContentPage>
```

![image](https://user-images.githubusercontent.com/2528888/88466752-a2847b00-ce9d-11ea-8832-6efc3dfe926c.png)
![image](https://user-images.githubusercontent.com/2528888/88466755-a912f280-ce9d-11ea-8aa1-4294aa978fa0.png)

``` xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:f9p="clr-namespace:Forms9Patch;assembly=Forms9Patch"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="ButtonBindingSample.MainPage"
             Padding="10"
             BackgroundColor="Black"
             >

    <StackLayout>
        <f9p:Button Text="Simple Button" TextColor="White" Command="{Binding CommandWithDisabledState}"/>
        <f9p:StateButton Text="State Button" TextColor="White" Command="{Binding CommandWithDisabledState}">
            <f9p:StateButton.DisabledState >
                <f9p:ButtonState TextColor="#4000" Text="StateButton - Disabled" />
            </f9p:StateButton.DisabledState>
        </f9p:StateButton>
        <Button Text="Xamarin Button" TextColor="White" Command="{Binding CommandWithDisabledState}"/>
        <f9p:Button Text="Toggle State" TextColor="White" DarkTheme="True" Command="{Binding ToggleCommand}"/>
    </StackLayout>

</ContentPage>

```
![image](https://user-images.githubusercontent.com/2528888/88466763-c2b43a00-ce9d-11ea-948f-e1b7aca8621b.png)
![image](https://user-images.githubusercontent.com/2528888/88466765-c8118480-ce9d-11ea-960f-c98df73e7990.png)

What I am driving at ... there are some scenarios where the Xamarin.Forms button disappears and there are some scenarios where the Forms9Patch.Button disappears.  

If you are looking to emulate Xamarin ...

``` xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:f9p="clr-namespace:Forms9Patch;assembly=Forms9Patch"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="ButtonBindingSample.MainPage"
             Padding="10"
             BackgroundColor="Black"
             >

    <StackLayout>
        <f9p:Button Text="Simple Button" TextColor="White" Command="{Binding CommandWithDisabledState}"/>
        <f9p:StateButton Text="State Button" TextColor="White" Command="{Binding CommandWithDisabledState}">
            <f9p:StateButton.DisabledState >
                <f9p:ButtonState TextColor="#4888" Text="StateButton - Disabled" />
            </f9p:StateButton.DisabledState>
        </f9p:StateButton>
        <Button Text="Xamarin Button" TextColor="White" Command="{Binding CommandWithDisabledState}"/>
        <f9p:Button Text="Toggle State" TextColor="White" DarkTheme="True" Command="{Binding ToggleCommand}"/>
    </StackLayout>

</ContentPage>
```

![image](https://user-images.githubusercontent.com/2528888/88466863-b11f6200-ce9e-11ea-803f-30841edb588b.png)

![image](https://user-images.githubusercontent.com/2528888/88466867-b7154300-ce9e-11ea-889f-f562669f8b03.png)



State button works pretty well with simple, in-line, changes.  If you were to use Xamarin's StateManager, you could get Forms9Patch.Button to behave the same way:

**Comment by baskren** [comment]
@michaelfoster9 

Since I haven't heard back from you on this in a couple of weeks, I'm going to close this issue.
