### ISSUE TITLE
[UIWebview Deprecation]

### ISSUE THREAD

**Issue by saeede29** [baskren/Forms9Patch#64]
Hello,
As u guys may know by now apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020.Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

to fix this in xamarin just have to follow simple steps:
https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/

Quote from Xamarin: "UIWebView can be present in some third party libraries, either managed or native that is used by your application. Start by updating your external dependencies to their latest versions since this situation might already be solved in a newer release. If not, contact the maintainer(s) of the libraries and ask about their update plans."

I am using Forms9Patch in my project. I wonder if Forms9Patch already covered this issue in their latest release?
 I can see in  ur project u r using SkiaSharp. as I know apps that r using  SkiaSharp are getting rejected by apple :
https://github.com/mono/SkiaSharp/issues/1271

it is a matter of emergency for our app and we need a release very soon. I would be grateful if u could help us on this.

Thanks

**Comment by baskren** [comment]
It's been a [couple of iterations of Forms9Patch since UIWebView was used.](https://github.com/baskren/Forms9Patch/blob/e8f1b532a853bb01101d16765625d322651cdea6/Forms9Patch/Forms9Patch.NuGet/Forms9Patch.nuspec#L78)  SkiaSharp does use UIWebView: https://github.com/mono/SkiaSharp/issues/1271#issuecomment-623660854.

**Comment by saeede29** [comment]
@baskren  yes I do understand that Forms9Patch does not use UIWebview I have checked your source code and saw u r using wkwebview but Forms9Patch does have a dependency on SkiaSharp.view.Form . so if the app using SkiaSharp getting rejected by apple the app using Forms9Patch will get rejected as well because of SkiaSharp Nuget .
