### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BamButz** [baskren/Forms9Patch#7]
Hello,

I came across this project and would like to expand one of my projects herewith.
However, I can not find a license and would like to know how to use the code to avoid legal consequences.

**Comment by baskren** [comment]
Forms9Patch using the MIT license.

**Comment by BamButz** [comment]
Alright, thanks for the information.
Maybe a LICENSE.md should be stored in the repository so that this is visible to future users. :)

**Comment by baskren** [comment]
LICENSE file has been added to the XF4 branch and will be merged into Master when deployed.
