### ISSUE TITLE
[Bug] When Forms9Patch loses shadow when disabled

### ISSUE THREAD

**Issue by smalgin** [baskren/Forms9Patch#71]
### Description

Button changes shape and loses shadow when disabled.

### Steps to Reproduce

1.  Open Forms9Patch.Demo.Nuget solution
2. Open Forms9Patch\Demo\Forms9PatchDemo.Common\Pages.Code\HtmlButtonsPage.cs and modify Tapped event:

```
        mb1.Tapped += (sender, e) =>
            {
                System.Diagnostics.Debug.WriteLine("Tapped");
                mb1.IsEnabled = false;
            };

```
3. Run Android project, select 'HTML Formatted Buttons' and tap top button ('Markup button'). Watch it lose shadow and expand.

It would be passable if it would not lose rounded corners... but it does. 
When button is image-only (no text, expanded image) - the effect is VERY visible and ugly.
### Expected Behavior

Button should not change shape.

### Actual Behavior

Button changes shape to rectangle.

### Basic Information

- Version with issue: 2.4.2
- Last known good version: Unknown
- IDE: Visual Studio 2019
- Platform Target Frameworks: only tested on Android
  - Android: Android 10 Q (could not install package on earlier platform version anyway)
- Nuget Packages:

### Screenshots

![image](https://user-images.githubusercontent.com/8367800/89983326-325f4e80-dc2c-11ea-9fe3-43bd7ac7a5fe.png)

### Reproduction Link - a link to a small demo project that reproduces this issue

https://github.com/baskren/Forms9Patch/tree/master/Demo/UsingForms9PatchNuGet
Change line https://github.com/baskren/Forms9Patch/blob/c910cab86e3a95f9d3bfca0b421fd55bdb0d5695/Demo/Forms9PatchDemo.Common/Pages.Code/HtmlButtonsPage.cs#L29 as described above.

### Workaround

Do not use Shadow, the difference is not so visible in this case.
I'll try to switch to SegmentedControl instead, it might work.

As always, I appreciate your great work. Please fix this when you get some time.

PS Looks like the icon image can't be positioned at the center of the button... pity. Background image requires drawn-in borders etc, so I thought about cutting some corners with IconImage... nope :)

**Comment by baskren** [comment]
This (mostly) functions as intended.  The shadow is an additional cue that the button is enabled.  Also, if you look closely, you can see that the corners have the same radii as the unshadowed version.

The only issue I can see is the size is different between the enabled and disabled version (because of the shadow padding).

**Comment by baskren** [comment]
I've fixed the change in size from enabled / disabled for HasShadow buttons.  This will be in the next release.

**Comment by baskren** [comment]
I've been using BackgroundImage for full sized & centered icon buttons for quite some time.  Not sure I understand the comment about drawn-in borders.

**Comment by smalgin** [comment]
Many thanks! 
Regarding buttons: I am still exploring button styling, so it might be user error, but when I use SVG file and empty text in the middle button, I get this awful thing:

![image](https://user-images.githubusercontent.com/8367800/90077067-0d172280-dcb6-11ea-90d6-36f92510ae98.png)

```
    <Forms9Patch:Button x:Name="nextButton" 
                    Grid.Column="1"
                    HeightRequest="50" 
                    HorizontalOptions="FillAndExpand"
                    TrailingIcon = "True"
                    HasTightSpacing = "True"
                    Spacing = "0"
                    BackgroundColor="{StaticResource GeneralButtonBackground}" 
                                    HasShadow="True"
                    TextColor="{StaticResource GeneralButtonText}"
                                    Text=""
                                    HorizontalTextAlignment="Center"
                    Command="{Binding NextPageCommand}"
                    IsEnabled="{Binding AdvanceEnabled}"
                  >
                    <Forms9Patch:Button.BackgroundImage>
                        <Forms9Patch:Image 
                            HeightRequest = "40"
                            HorizontalOptions="CenterAndExpand"
                            BackgroundColor="{StaticResource GeneralButtonBackground}" 
                            VerticalOptions="Center"
                            Source="{localcommon:ImageMultiResource HSM.Assessor.Resources.iconmonstr-next-thin.svg}"/>
                    </Forms9Patch:Button.BackgroundImage>

                </Forms9Patch:Button>
```

No borders and no shadow, even when Shadow is set to true.

The white space on the left and right of background image is still button, it's clickable.
I wonder if I get better by switching from SVG to multitude of PNGs...

No worries, I'll figure it out eventually.
The button is big enough for text, so I use text instead of background image and it works perfectly.

**Comment by baskren** [comment]
Are you referring to the apparent difference in padding between the button border and the lines of the artwork for the back button vs the forward button?

**Comment by smalgin** [comment]
The forward button is actually quite large: I overlaid green rectangle (via Paint editor) to show actual button layout rectangle:
![image](https://user-images.githubusercontent.com/8367800/90195114-87f74080-dd7d-11ea-9b3b-5076505392ff.png)

I can click anywhere inside of the button area to make it work.

I'll get demo project for this some time in future :)

**Comment by baskren** [comment]
Sounds like a couple of things are going on here.  First, the type of layout container (the button's parent) and the button's LayoutOptions need to be considered.  If you're using a StackLayout (and, in Xamarin, you almost always shouldn't) and the button's HorizontalOptions = LayoutOptions.Fill, then that's the a big part of it.

Also, paths in the SVG source files, relative to the page boundaries (of the SVG file) could be not the same between the forward and backwards buttons. 

I'm sure there's other things not quite right.
