### ISSUE TITLE
[Bug] OpenSansBold font is not loaded on Android from 2.4.0-beta1

### ISSUE THREAD

**Issue by matibak** [baskren/Forms9Patch#78]
### Description
OpenSansBold font is not loaded on Android from 2.4.0-beta1. Default font is displayed.
### Expected Behavior
Custom font displayed in Label.
### Actual Behavior
Default font displayed in Label.
### Basic Information

- Version with issue: 2.4.0-beta1 onwards
- Last known good version: 2.3.0
- IDE: Rider
- Nuget Packages: Xamarin.Forms 4.8.0.1269

### Reproduction Link - a link to a small demo project that reproduces this issue

[font.zip](https://github.com/baskren/Forms9Patch/files/5332517/font.zip)

**Comment by Symorp** [comment]
Same issue here

**Comment by baskren** [comment]
Fixed in version 2.4.7
