### ISSUE TITLE
Cannot find assembly on IOS project.

### ISSUE THREAD

**Issue by KCarterSr** [baskren/Forms9Patch#8]
Getting error,   Cannot find the assembly 'SkiaSharp.Svg, Version=1.59.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' referenced from '/Users/cwmdev/Library/Caches/Xamarin/mtbs/builds/C.W.MatthewsStarterTemplateIOS/a01f70ea142e4d1d62eb62a0640da97a/bin/iPhoneSimulator/Debug/Forms9Patch.dll'.

I've checked the path listed and there is a SkiaSharp.Extended.Svg.dll but no SkiaSharp.Svg.dll 

This ONLY HAPPENS on the IOS project. On UWP etc.. EVERYTHIG IS OK.

SkiaSharp version is 1.68.0.0

Thanks

**Comment by baskren** [comment]
Two suggestions:
1. I am guessing you have already done this ... add the SkiaSharp.Views.Forms (1.59.3) and SkiaSharp.Svg (1.59.0) NuGet packages to your iOS project.
2. Version 1.8 will be out later this week.  You might want to re-evaluate using this version.

**Comment by baskren** [comment]
Were you able to resolve this?

**Comment by KCarterSr** [comment]
New update seems to have fixed this problem.
Thanks
