### ISSUE TITLE
[Bug] LineHeight not working (Android)

### ISSUE THREAD

**Issue by AlleSchonWeg** [baskren/Forms9Patch#82]
### Description
On Android LineHeight is ignored. On iOS it works. Repro App uses Text-Property. But HtmlText doesn't work too.

### Steps to Reproduce

1. Run sample App on Android

### Basic Information
XAML:
```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:Forms9Patch="clr-namespace:Forms9Patch;assembly=Forms9Patch"
             x:Class="Forms9HtmlStyle.MainPage">
  <StackLayout>
   <Forms9Patch:Label LineHeight="2"
                       Text="LineHeight OnAndroid not working LineHeight OnAndroid not working LineHeight OnAndroid not working LineHeight OnAndroid not working LineHeight OnAndroid not working LineHeight OnAndroid not working "
                       x:Name="lineHeight" />
  </StackLayout>
</ContentPage>
```

- Version with issue: 2.4.8
- Last known good version:
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![Unbenannt](https://user-images.githubusercontent.com/6727366/100602261-f697e400-3303-11eb-9e7c-8d2ab8e3917d.PNG)

### Workaround

[Forms9HtmlStyle.zip](https://github.com/baskren/Forms9Patch/files/5615548/Forms9HtmlStyle.zip)

**Comment by baskren** [comment]
please try version 2.4.9-beta1 and let me know if it fixes this issue

**Comment by AlleSchonWeg** [comment]
Hi,
yes it fixes this issue.

**Comment by baskren** [comment]
Great!  Thanks for taking the time to test the update!
