### ISSUE TITLE
[Bug] HtmlText Inline style with space char

### ISSUE THREAD

**Issue by AlleSchonWeg** [baskren/Forms9Patch#83]
### Description
 Using HtmlText Property with this html string:

> "color: <div style=\"color: #7fb22d\">#7fb22d Text</div> plain"

will not work. But if the following string it works:

> "color: <div style=\"color:#7fb22d\">#7fb22d Text</div> plain"

The difference is only the space char between : and #. Same behavior on iOS and Android.

### Steps to Reproduce

1. Run sample App

### Expected Behavior
Control should ignore space char in style attribute and apply color.

### Actual Behavior
Control displays no text.

### Basic Information

- Version with issue: 2.4.8
- Last known good version:
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![Unbenannt](https://user-images.githubusercontent.com/6727366/100603548-8e4a0200-3305-11eb-804e-596f10cbb3a2.PNG)

### Reproduction Link - a link to a small demo project that reproduces this issue

[Forms9HtmlStyle.zip](https://github.com/baskren/Forms9Patch/files/5615597/Forms9HtmlStyle.zip)

**Comment by baskren** [comment]
please try version 2.4.9-beta1 and let me know if it fixes this issue

**Comment by AlleSchonWeg** [comment]
Hi,
yes it fixes this issue.

**Comment by baskren** [comment]
Super!  Once again, thank you for testing the update.
