### ISSUE TITLE
[Bug] Android crashes when a system font has been added as an asset or resource

### ISSUE THREAD

**Issue by EGoverde** [baskren/Forms9Patch#85]
### Description
In the logic where all fonts are loaded on Android from system, assets and resources a single dictionary is created by merging from these sources. It is possible for the same named fonts to exists in more than one source (both system and asset for example). If so the AddRange() will fail, because the key already exists in the Dictionary.

### Steps to Reproduce

1. Add Forms9Patch to a Forms project
2. Add Roboto font to assets (or add SyncFusion library, which includes it)
3. Run app on Android 6 (which includes Roboto as system font)
4. Render a label with HTML, app crashes

### Expected Behavior
The label renders as expected, without crashing the app.

### Actual Behavior
The app crashes with a "System.ArgumentException: An item with the same key has already been added. Key: Roboto#Regular" at FontManagment.cs.

### Basic Information
- Version with issue: 2.4.8
- Last known good version: -
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - Android: At least 6.0, likely all versions if adding fonts manually
- Android Support Library Version: AndroidX.LegacySupport.V4 1.0.0.5
- Nuget Packages: SyncFusion.Xamarin.SfPopupLayout
- Affected Devices: Likely all Android devices if adding fonts manually

### Screenshots
![afbeelding](https://user-images.githubusercontent.com/3169710/101337629-31f25f80-387c-11eb-98a3-582f9cdd5243.png)

### Reproduction Link - a link to a small demo project that reproduces this issue
Will follow-up if requested, but a PR has already been created to fix this relative simple issue:
https://github.com/baskren/Forms9Patch/pull/84/commits/2eeab9ba49a65f6b3540c680869176518f7a84d5

### Workaround
The only work-around seems to be avoiding adding duplicate fonts, which is difficult if another library is adding it.

**Comment by mubaarakhassan** [comment]
Yes, i am having this issue too.

**Comment by baskren** [comment]
please try version 2.4.9-beta1 and let me know if it fixes this issue

**Comment by EGoverde** [comment]
I can confirm it works @baskren, thanks!

**Comment by baskren** [comment]
Great to hear this.  And @EGoverde ,  thank you again for the great analysis and PR.
