### ISSUE TITLE
[Bug] Toast error message in productive app when missing picture

### ISSUE THREAD

**Issue by GW-FUB** [baskren/Forms9Patch#86]
### Description
When an referenced image is missing a toast message ist saying "Cannot find EmbeddedResource". There should be a possibility to disable this in productive apps.

### Steps to Reproduce

1. Use a forms9Patch.Image in XAML
2. Set the source to something random (e.g. "notexistingimage.png")
3. A toast message appears "Cannot find EmbeddedResource"

### Expected Behavior
No toast in production

### Actual Behavior
A toast message

**Comment by baskren** [comment]
@GW-FUB 

I'll be added a new property to the Image class: FailAction (of enum type Forms9Patch.FailAction).  This will allow you to either:
- Ignore
- ShowAlert
- ThrowException

There are some other places where it would be nice to have this as well.  For now, I'll be adding optional FailAction arguments to the PrintAsync WebView extension methods.

**Comment by baskren** [comment]
please take a look at version 2.4.9-beta1 and let me know if it fixes this issue.  Try out the Image.FailAction property and let me know if this works for you.

**Comment by GW-FUB** [comment]
@baskren Yes, works great. Thanks

**Comment by baskren** [comment]
Super!  Thanks for taking a look.
