### ISSUE TITLE
[Bug] Icons not showing on buttons on Android

### ISSUE THREAD

**Issue by chrisfoulds** [baskren/Forms9Patch#87]
### Description
On the latest version of the library on Android the icons on the buttons are no longer working.

### Steps to Reproduce

This works and shows icons on both platforms
```
                <Image HeightRequest="35" Margin="10,6,6,0"  VerticalOptions="CenterAndExpand" Grid.Row="0" Grid.Column="0">
                    <Image.Source>
                        <FontImageSource
                                FontFamily="{DynamicResource FontAwesomeRegular}"
                                Glyph="{StaticResource LeftArrow}"
                                Size="44"
                                Color="White" />
                    </Image.Source>
                </Image>
```

This however only works on iOS`
<f9p:Button VerticalOptions="CenterAndExpand" Clicked="Faster_Clicked" Text="Faster Times" IconText="{StaticResource TachFast}" IconFontFamily="{DynamicResource FontAwesomeRegular}" BackgroundColor="{StaticResource OrangeButton}"  HasTightSpacing="True" TrailingIcon="False" ElementShape="Obround"  HasShadow="True" HorizontalTextAlignment="Center" Spacing="35" Margin="5" FontSize="14" FontFamily="{DynamicResource RobotoBold}"  TextColor="White"/>`

### Expected Behavior
Works the same as iOS

### Actual Behavior
Blank icons

### Basic Information
Latest forms & forms9patch

### Screenshots
![Screenshot_20201214-140049](https://user-images.githubusercontent.com/16035209/102090139-fecc4500-3e14-11eb-8090-034057f86287.png)
![IMG_2427](https://user-images.githubusercontent.com/16035209/102090155-01c73580-3e15-11eb-8eb1-8069604c2cfe.jpg)

**Comment by baskren** [comment]
Please send a demo project that replicates this issue.

**Comment by baskren** [comment]
Yeah, definitely send me a demo project.  It's not clear to me you're touching Forms9Patch with the sample XAML you've shared nor is it clear that this is within the scope of Forms9Patch.

**Comment by chrisfoulds** [comment]
Sure attaching along with screenshots showing the button not working on droid

**Comment by chrisfoulds** [comment]
[Uploading demoproblem.zip…]()

**Comment by chrisfoulds** [comment]
![Screenshot_1608117081](https://user-images.githubusercontent.com/16035209/102341429-bc7b4300-3f8f-11eb-9b8e-8b9d46ae6eba.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-12-16 at 11 07 28](https://user-images.githubusercontent.com/16035209/102341435-be450680-3f8f-11eb-8dd2-a93a684566a1.png)

**Comment by chrisfoulds** [comment]
[demoproblem.zip](https://github.com/baskren/Forms9Patch/files/5702234/demoproblem.zip)

**Comment by baskren** [comment]
please verify fix with version 2.4.9-beta2

**Comment by chrisfoulds** [comment]
Yep that works - thanks

**Comment by chrisfoulds** [comment]
[
<img width="496" alt="Screenshot 2020-12-16 at 14 54 32" src="https://user-images.githubusercontent.com/16035209/102364674-a16bfb80-3fae-11eb-83e1-1d84ec4b2c93.png">
]

**Comment by baskren** [comment]
Thank you for taking the time to verify this.  v2.4.9 is now released.
