### ISSUE TITLE
Images not shown on iOS device

### ISSUE THREAD

**Issue by OmarHassan25** [baskren/Forms9Patch#9]
9-Patch Images are not drawn on IOS device but work well on the simulator, any advise?

**Comment by baskren** [comment]
The Forms9PatchDemo app has 9Patch images in it and they are rendering on my iPhone and iPad - so I'm guessing there is something in your project that is triggering this issue.  

With that in mind, I have two suggestions:
1. Can you send me a sample project that demonstrates this issue?  This is the only way I will be able to replicate your issue, given the information available.
2. Version 1.8 will be out later this week.  There are changes in the rendering engine so it might be worth re-evaluating with this version.

**Comment by baskren** [comment]
@OmarHassan25 : Is this issue still present for you?

**Comment by OmarHassan25** [comment]
No, it disappeared by itself, I don't know what was the reason for it.
